version: '3'
services:
    frontend:
        container_name: frontend
        build:
            context: .
            dockerfile: Dockerfile-frontend
        depends_on:
          - backend
        ports:
          - "8080:8080"
        hostname: frontend
        user: root
        stdin_open: true
        tty: true
    backend:
        container_name: backend
        build:
            context: .
            dockerfile: Dockerfile-backend
        ports:
          - "8000:8000"
        hostname: backend
        user: root
        stdin_open: true
        tty: true
